name: terraform-stg-infra-deploy

on:
  push:
    branches: [ staging ]
    paths:
    - ['*.tf', '.terraform/**', '.terraform.lock.hcl']

  workflow_dispatch:

jobs:

  terraform:

    name: Terraform Integration (stg)
    runs-on: ubuntu-latest
    environment: staging

    steps:

      - uses: actions/checkout@v2

      # Install Terraform & Terraform Cloud on the job woker + authenticate with the CLOUD TOKEN
      - name: Install Terraform & Authenticate on Terraform Cloud
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.6
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
      
      # Init the .terraform.lock.hcl (contains init state for providers, resources, etc.)
      # Initialised on the 'cete-api-default' workspace. TF will switch the workspace when needed (ie applying) 
      - name: Run 'terraform init'
        id: init
        env:
          TF_WORKSPACE: cete-api-default
        run: |
          terraform init -upgrade

      # On PUSH events to the main branch, APPLY the generated Terraform plan to the correct environment
      # Changes workspace based on branch : staging = cete-stg-infra; main = cete-prd-infra
      - name: Run 'terraform apply' (stg)
        run: |
          terraform workspace select cete-stg-infra
          terraform apply -auto-approve -var="ENVIRONMENT="stg""
