name: terraform-prd-infra-deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  terraform:

    name: Terraform Integration (prd)
    runs-on: ubuntu-latest
    environment: production

    steps:

      - uses: actions/checkout@v2

      # Create an automatically bumped, indexed tag and push it to the branch
      - name: Bump Version and Push Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}

      # Create a GH Release using the output of the tag_version step
      - name: Create a GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      # Install Terraform & Terraform Cloud on the job woker + authenticate with the CLOUD TOKEN
      - name: Install Terraform & Authenticate on Terraform Cloud
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.6
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
      
      # Init the .terraform.lock.hcl (contains init state for providers, resources, etc.)
      # Initialised on the 'cete-api-default' workspace. TF will switch the workspace when needed (ie applying) 
      - name: Run 'terraform init'
        id: init
        env:
          TF_WORKSPACE: cete-api-default
        run: |
          terraform init -upgrade

      # On PUSH events to the main branch, APPLY the generated Terraform plan to the correct environment
      # Changes workspace based on branch : staging = cete-stg-infra; main = cete-prd-infra
      - name: Run 'terraform apply' (prd)
        run: |
          terraform workspace select cete-prd-infra
          terraform apply -auto-approve -var="ENVIRONMENT="prd""